# Generated by Django 4.1.7 on 2023-07-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='image')),
                ('natural_image_name', models.CharField(max_length=128, unique=True, verbose_name='not_hashable_name')),
            ],
            options={
                'verbose_name': 'reducer',
                'verbose_name_plural': 'reducers',
            },
        ),
    ]
